services:
  db:
   image: postgres
   restart: always
   shm_size: 128mb
   environment:
     POSTGRES_PASSWORD: 123456abc
     POSTGRES_USER: cody
     POSTGRES_DB: templateAPIdb
   networks:
      - internal
   volumes:
     - ./sql:/docker-entrypoint-initdb.d
    #  - ./dbdata:/var/lib/postgresql/data
   # ports:
   #   - 5432:5432
   # command: ["postgres", "-c", "log_statement=all"] # Enables verbose logging

    
  api:  
    image: codyhowl/agentic-api:build-13
    restart: always
    environment:
      - DOTNET_DATABASE_STRING=Host=db;Database=templateAPIdb;Username=cody;Password=123456abc;
      - AI_TOKEN=loremtoken
    networks:
      - web
      - internal
    depends_on:
      - db
    ports:
      - 4110:8080

networks:
  internal:
  web:
    external: true
