services:
  db:
   image: postgres
   restart: always
   shm_size: 128mb
   environment:
     POSTGRES_PASSWORD: 123456abc
     POSTGRES_USER: cody
     POSTGRES_DB: agentDb
   volumes:
     - ./sql:/docker-entrypoint-initdb.d
    #  - ./dbdata:/var/lib/postgresql/data
   ports:
     - 5432:5432
   # command: ["postgres", "-c", "log_statement=all"] # Enables verbose logging

    
  api:  
    build:
      context: .
      dockerfile: ./AgentAPI/Dockerfile
    restart: always
    environment:
      - DOTNET_DATABASE_STRING=Host=db;Database=agentDb;Username=cody;Password=123456abc;
      - AI_TOKEN=${AI_TOKEN}
      - AI_SERVER_URL=https://ai-snow.reindeer-pinecone.ts.net/api/chat/completions
    depends_on:
      - db
    ports:
      - 4110:8080
    # Mount host data_repo into the container at /data_repo so data isn't baked into the image
    volumes:
      - ./data_repo:/data_repo:rw


