services:
  db:
   image: postgres
   restart: always
   shm_size: 128mb
   environment:
     POSTGRES_PASSWORD: 123456abc
     POSTGRES_USER: cody
     POSTGRES_DB: agentDb
   networks:
      - internal
   volumes:
     - ./sql:/docker-entrypoint-initdb.d
    #  - ./dbdata:/var/lib/postgresql/data
   # ports:
   #   - 5432:5432
   # command: ["postgres", "-c", "log_statement=all"] # Enables verbose logging

    
  api:  
    image: codyhowl/agentic-api:build-38
    restart: always
    environment:
      - DOTNET_DATABASE_STRING=Host=db;Database=agentDb;Username=cody;Password=123456abc;
      - AI_TOKEN=${AI_TOKEN}
      - AI_SERVER_URL=https://ai-snow.reindeer-pinecone.ts.net/api/chat/completions
    networks:
      - web
      - internal
    depends_on:
      - db
    ports:
      - 8080:8080
    # In prod we also mount the host ./data_repo so the runtime uses external data
    volumes:
      - ./data_repo:/data_repo:ro

networks:
  internal:
  web:
    external: true
